### ISSUE TITLE
fileutils.rb:1378:in `copy': cannot handle socket (RuntimeError)

### ISSUE THREAD

**Issue by gwm0415** [testmycode/tmc-server#488]
when i run the command "`rvmsudo rake spec`"， that shows

```
/usr/local/rvm/rubies/ruby-2.2.2/bin/ruby -I/usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib:/usr/local/rvm/gems/ruby-2.2.2/gems/rspec-support-3.5.0/lib /usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Coverage report generated for RSpec to /home/tmc/tmc-server/coverage. 289 / 11187 LOC (2.58%) covered.
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1378:in `copy': cannot handle socket (RuntimeError)
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:471:in `block in copy_entry'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1497:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1497:in `wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1500:in `block in wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1499:in `each'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1499:in `wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1500:in `block in wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1499:in `each'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1499:in `wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1500:in `block in wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1499:in `each'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1499:in `wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1500:in `block in wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1499:in `each'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1499:in `wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:468:in `copy_entry'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:443:in `block in cp_r'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1584:in `fu_each_src_dest0'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:442:in `cp_r'
	from /home/tmc/tmc-server/spec/support/remote_sandbox_for_testing.rb:78:in `copy_server_instance'
	from /home/tmc/tmc-server/spec/support/remote_sandbox_for_testing.rb:37:in `block in init_servers_as_root!'
	from /home/tmc/tmc-server/spec/support/remote_sandbox_for_testing.rb:36:in `each'
	from /home/tmc/tmc-server/spec/support/remote_sandbox_for_testing.rb:36:in `init_servers_as_root!'
	from /home/tmc/tmc-server/spec/spec_helper.rb:31:in `block in <top (required)>'
	from /home/tmc/tmc-server/spec/spec_helper.rb:44:in `call'
	from /home/tmc/tmc-server/spec/spec_helper.rb:44:in `<top (required)>'
	from /home/tmc/tmc-server/spec/controllers/api/v8/apidocs_controller_spec.rb:1:in `require'
	from /home/tmc/tmc-server/spec/controllers/api/v8/apidocs_controller_spec.rb:1:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'
/usr/local/rvm/rubies/ruby-2.2.2/bin/ruby -I/usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib:/usr/local/rvm/gems/ruby-2.2.2/gems/rspec-support-3.5.0/lib /usr/local/rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by Distorzion** [comment]
Did you solve the problem?
