### ISSUE TITLE
maven.testmycode.net times out while running rake compile

### ISSUE THREAD

**Issue by laurirasanen** [testmycode/tmc-server#498]
Following the installation instructions for Ubuntu 14.04 fails at step [Compile rest of the externals](https://github.com/testmycode/tmc-server/blob/master/Installation.md#compile-rest-of-the-externals).
```sh
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] build-tools 1.0 .................................... SUCCESS [  3.141 s]
[INFO] tmc-langs 1.0-SNAPSHOT ............................. SUCCESS [37:11 min]
[INFO] tmc-langs-framework 1.0-SNAPSHOT ................... FAILURE [10:54 min]
[INFO] tmc-langs-java 1.0-SNAPSHOT ........................ SKIPPED
[INFO] tmc-langs-make 1.0-SNAPSHOT ........................ SKIPPED
[INFO] tmc-langs-python3 1.0-SNAPSHOT ..................... SKIPPED
[INFO] tmc-langs-notests 1.0-SNAPSHOT ..................... SKIPPED
[INFO] tmc-langs-util 1.0-SNAPSHOT ........................ SKIPPED
[INFO] tmc-langs-cli 1.0-SNAPSHOT ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  48:10 min
[INFO] Finished at: 2020-03-24T12:08:47Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project tmc-langs-framework: Could not resolve dependencies for project fi.helsinki.cs.tmc:tmc-langs-framework:jar:1.0-SNAPSHOT: Failed to collect dependencies at fi.helsinki.cs.tmc:tmc-langs-abstraction:jar:1.0.0: Failed to read artifact descriptor for fi.helsinki.cs.tmc:tmc-langs-abstraction:jar:1.0.0: Could not transfer artifact fi.helsinki.cs.tmc:tmc-langs-abstraction:pom:1.0.0 from/to testmycode.net (http://maven.testmycode.net/nexus/content/repositories/releases/): Connect to maven.testmycode.net:80 [maven.testmycode.net/148.251.139.135] failed: Connection timed out (Connection timed out) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :tmc-langs-framework
/home/tmc/tmc-server/lib/system_commands.rb:45:in `sh!'
/home/tmc/tmc-server/lib/maven_project.rb:61:in `block in compile!'
/home/tmc/tmc-server/lib/maven_project.rb:60:in `chdir'
/home/tmc/tmc-server/lib/maven_project.rb:60:in `compile!'
/home/tmc/tmc-server/lib/maven_project.rb:77:in `block (2 levels) in make_rake_tasks'
/var/lib/gems/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => compile => tmc-langs:compile => /home/tmc/tmc-server/ext/tmc-langs/tmc-langs-cli/target/tmc-langs-cli-1.0-SNAPSHOT.jar
(See full trace by running task with --trace)
```

**Comment by nygrenh** [comment]
Yeah, that repo has moved to to maven.mooc.fi. You can try to update the tmc-langs submodule as a temporary workaround.

**Comment by laurirasanen** [comment]
Updating tmc-langs to master branch works 👍
